# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2025-04-19 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20250419_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
