# Generated by Django 3.2.25 on 2025-05-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
